# Generated by Django 5.0.3 on 2024-05-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_tag_post_category_post_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tegs',
            field=models.ManyToManyField(related_name='tag_posts', to='blog.tag'),
        ),
    ]
