# Generated by Django 5.0.3 on 2024-05-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='messsage',
            new_name='message',
        ),
    ]
