# Generated by Django 5.0.3 on 2024-05-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_messsage_postcomment_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Post Comments'},
        ),
    ]
