# Generated by Django 5.0.3 on 2024-05-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tegs',
            new_name='tags',
        ),
    ]
